name: domino_game
description: domino_game_online_offline

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.19
  google_fonts: ^4.0.3
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  fluttertoast: ^8.1.3
  shared_preferences: ^2.0.18
  animated_text_kit: ^4.2.2
  lottie: ^2.3.1
  flutter_svg: ^2.0.4
  image_picker: ^0.8.7+1
  connectivity_plus: ^2.2.0
  flutter_offline: ^2.1.0
  device_information: ^0.0.4
  permission_handler: ^10.2.0

  ###############################
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  flutter_facebook_auth: ^5.0.8
  google_sign_in: ^6.1.0
  firebase_storage: ^11.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_native_splash:
  color: "#071C21"
  image: assets/images/splash_logo.png
  image_dark: assets/images/splash_logo.png
  color_dark: "#071C21"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # see https://flutter.dev/custom-fonts/#from-packages
